// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAwGMIWur9gzsDGCe4nWcZTgzs3LNOPANQ',
//     appId: '1:761508087869:web:00e6d1d333b475deffc254',
//     messagingSenderId: '761508087869',
//     projectId: 'sandol-58497',
//     authDomain: 'sandol-58497.firebaseapp.com',
//     storageBucket: 'sandol-58497.appspot.com',
//     measurementId: 'G-SBYVCXFCBH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC0a4imr9Q-eNa4XL8Wytvk7Tn9UMZxr0k',
//     appId: '1:761508087869:android:a16d578cfcbe4583ffc254',
//     messagingSenderId: '761508087869',
//     projectId: 'sandol-58497',
//     storageBucket: 'sandol-58497.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBf8tnmRqsDWCXmW0NQioZcH3Fsmr-Svpc',
//     appId: '1:761508087869:ios:40e150b259e29b6fffc254',
//     messagingSenderId: '761508087869',
//     projectId: 'sandol-58497',
//     storageBucket: 'sandol-58497.appspot.com',
//     iosClientId: '761508087869-o8bkj01k5oe0vv24dcdedgcka9po6p68.apps.googleusercontent.com',
//     iosBundleId: 'com.example.test',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBf8tnmRqsDWCXmW0NQioZcH3Fsmr-Svpc',
//     appId: '1:761508087869:ios:40e150b259e29b6fffc254',
//     messagingSenderId: '761508087869',
//     projectId: 'sandol-58497',
//     storageBucket: 'sandol-58497.appspot.com',
//     iosClientId: '761508087869-o8bkj01k5oe0vv24dcdedgcka9po6p68.apps.googleusercontent.com',
//     iosBundleId: 'com.example.test',
//   );
// }
